#!/usr/bin/env sh
echo "This script runs before every commit!"
. "$(dirname -- "$0")/_/husky.sh"

if git log --format=%B -n 1 HEAD | grep -q "chore(release):"; then
  exit 0
fi

npm run lint
npm run prettier
npm run release
git add .